name: Cron Job Test

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Print a test message
        run: echo "Cron job triggered at $(date)"
