name: Check Repositories for Tomer Creations

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List all repositories
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Retrieve the list of repositories the token has access to
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/orgs/ORG_NAME/repos?per_page=100)  # Replace ORG_NAME with your organization

          # Print the raw response for debugging purposes
          echo "API Response: $response"

          # Check if the response is valid JSON
          if echo "$response" | jq empty; then
            echo "$response" | jq -r '.[] | .name' > repo_list.txt
          else
            echo "Failed to retrieve repositories: $response"
            exit 1  # Exit if the response is not valid JSON
          fi

      - name: Check if Tomer created the repo and it’s not a fork
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TOMER_USERNAME: "tomeroz802"  # Your GitHub username
        run: |
          while read repo; do
            repo_info=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/$TOMER_USERNAME/$repo)

            owner=$(echo "$repo_info" | jq -r '.owner.login')
            creator=$(echo "$repo_info" | jq -r '.owner.type')
            fork=$(echo "$repo_info" | jq -r '.fork')

            if [ "$owner" == "$TOMER_USERNAME" ] && [ "$creator" == "User" ] && [ "$fork" == "false" ]; then
              echo "Tomer created $repo and it is not a fork"
            else
              echo "$repo was not created by Tomer or is a fork"
            fi
          done < repo_list.txt
