name: Setup New Repository

on:
  repository:
    types: [created]

jobs:
  setup-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Assign team permissions
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.AutomationToken }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/your-org/teams/your-team/repos/${{ github.repository_owner }}/${{ github.event.repository.name }} \
            -d '{"permission":"push"}'

      - name: Grant repo owner admin permissions
        run: |
          REPO_OWNER=$(curl -s \
            -H "Authorization: token ${{ secrets.AutomationToken }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }} \
            | jq -r .owner.login)
          
          curl -X PUT \
            -H "Authorization: token ${{ secrets.AutomationToken }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/collaborators/$REPO_OWNER \
            -d '{"permission":"admin"}'
