name: Scheduled Permission Check

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  check-new-repos:
    runs-on: ubuntu-latest

    steps:
      - name: List repositories
        id: list_repos
        uses: octokit/request-action@v2.x
        with:
          route: GET /orgs/:org/repos
          org: your-organization
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply permissions to new repositories
        run: |
          echo "Checking repositories..."
          for repo in $(jq -r '.[].name' <<< "${{ steps.list_repos.outputs.data }}"); do
            if [[ $repo == *"-new-repo-pattern-"* ]]; then
              echo "Granting permissions to $repo..."
              curl -X PUT \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/orgs/your-organization/teams/your-team-name/repos/your-organization/$repo \
                -d '{"permission":"push"}'
            fi
          done
