name: Grant Permissions Manually

on:
  workflow_dispatch:

jobs:
  grant-permissions:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the owner is tomer
        run: |
          if [ "${{ github.event.inputs.owner }}" != "tomeroz802" ]; then
            echo "Owner is not tomer, skipping permission grant."
            exit 0
          fi

      - name: Grant permissions to the team
        uses: octokit/request-action@v2.x
        with:
          route: PUT /orgs/:org/teams/:team_name/repos/:owner/:repo
          org: ${{ github.event.inputs.organization }}
          team_name: your-team-name
          owner: ${{ github.event.inputs.owner }}
          repo: ${{ github.event.inputs.repo }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
