name: Handle Repository Creation

on:
  repository_dispatch:
    types: [repository-created]

jobs:
  grant-permissions:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the owner is tomer
        run: |
          if [ "${{ github.event.client_payload.owner }}" != "tomer" ]; then
            echo "Owner is not tomer, skipping permission grant."
            exit 0
          fi

      - name: Grant permissions to the team
        uses: octokit/request-action@v2.x
        with:
          route: PUT /orgs/:org/teams/:team_name/repos/:owner/:repo
          org: ${{ github.event.client_payload.organization }}
          team_name: your-team-name
          owner: ${{ github.event.client_payload.owner }}
          repo: ${{ github.event.client_payload.repo }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
