name: Grant Team Permissions on Repository Creation

on:
  repository_dispatch:
    types: [repository-created]

jobs:
  add-team-permissions:
    runs-on: ubuntu-latest

    steps:
      - name: Check if owner is tomer
        id: check-owner
        run: |
          if [ "${{ github.event.client_payload.owner }}" != "tomer" ]; then
            echo "Not the correct owner, skipping..."
            exit 0
          fi

      - name: Grant permissions to team
        if: steps.check-owner.outputs.result != '0'
        uses: octokit/request-action@v2.x
        with:
          route: PUT /orgs/:org/teams/:team_name/repos/:owner/:repo
          org: ${{ github.event.client_payload.organization }}
          team_name: your-team-name
          owner: ${{ github.event.client_payload.owner }}
          repo: ${{ github.event.client_payload.repo }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
