name: Grant Team Permissions on Repository Creation

on:
  repository_dispatch:
    types: [repository-created]

jobs:
  add-team-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Grant permissions to team
        uses: octokit/request-action@v2.x
        with:
          route: PUT /orgs/:org/teams/:team_name/repos/:owner/:repo
          org: ${{ github.event.client_payload.organization }}
          team_name: your-team-name
          owner: ${{ github.event.client_payload.owner }}
          repo: ${{ github.event.client_payload.repo }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
