name: Check Repositories for Tomer Creations

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List all repositories
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATIONTOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/user/repos?per_page=100 \
          | jq -r '.[] | .name' > repo_list.txt

      - name: Check if Tomer created the repo
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATIONTOKEN }}
          TOMER_USERNAME: "YOUR_USERNAME"  # Your GitHub username
        run: |
          while read repo; do
            repo_info=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/$TOMER_USERNAME/$repo)

            owner=$(echo "$repo_info" | jq -r '.owner.login')
            creator=$(echo "$repo_info" | jq -r '.owner.type')
              
            if [ "$owner" == "$TOMER_USERNAME" ] && [ "$creator" == "User" ]; then
              echo "Tomer created $repo, adding tickets group"
              curl -s -H "Authorization: token $GITHUB_TOKEN" \
                -X PUT -d '{"permission":"push"}' \
                https://api.github.com/repos/$TOMER_USERNAME/$repo/collaborators/tickets
            else
              echo "$repo was not created by Tomer"
            fi
          done < repo_list.txt
