name: Trigger on Repo Creation

on:
  repository_dispatch:
    types: [repo_created]

jobs:
  run-on-repo-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run your script or action
        run: echo "Repository created! Running custom actions."
